export const FILMS = [
  {
    adult: false,
    backdrop_path: '/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg',
    genre_ids: [12, 28, 878],
    id: 11,
    original_language: 'en',
    original_title: 'Star Wars',
    overview:
      'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
    popularity: 133.018,
    poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
    release_date: '1977-05-25',
    title: 'Star Wars',
    video: false,
    vote_average: 8.204,
    vote_count: 19364,
    details: {
      adult: false,
      backdrop_path: '/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 11000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage: 'http://www.starwars.com/films/star-wars-episode-iv-a-new-hope',
      id: 11,
      imdb_id: 'tt0076759',
      original_language: 'en',
      original_title: 'Star Wars',
      overview:
        'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire.',
      popularity: 133.018,
      poster_path: '/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 25,
          logo_path: '/qZCc1lty5FzX30aOCVRBLzaVmcp.png',
          name: '20th Century Fox',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '1977-05-25',
      revenue: 775398007,
      runtime: 121,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'A long time ago in a galaxy far, far away...',
      title: 'Star Wars',
      video: false,
      vote_average: 8.204,
      vote_count: 19363,
    },
  },
  {
    adult: false,
    backdrop_path: '/epVMXf10WqFkONzKR8V76Ypj5Y3.jpg',
    genre_ids: [12, 28, 878],
    id: 181808,
    original_language: 'en',
    original_title: 'Star Wars: The Last Jedi',
    overview:
      'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.',
    popularity: 57.393,
    poster_path: '/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg',
    release_date: '2017-12-13',
    title: 'Star Wars: The Last Jedi',
    video: false,
    vote_average: 6.818,
    vote_count: 14443,
    details: {
      adult: false,
      backdrop_path: '/epVMXf10WqFkONzKR8V76Ypj5Y3.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 200000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage:
        'https://www.starwars.com/films/star-wars-episode-viii-the-last-jedi',
      id: 181808,
      imdb_id: 'tt2527336',
      original_language: 'en',
      original_title: 'Star Wars: The Last Jedi',
      overview:
        'Rey develops her newly discovered abilities with the guidance of Luke Skywalker, who is unsettled by the strength of her powers. Meanwhile, the Resistance prepares to do battle with the First Order.',
      popularity: 57.393,
      poster_path: '/kOVEVeg59E0wsnXmF9nrh6OmWII.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2017-12-13',
      revenue: 1332698830,
      runtime: 152,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Darkness rises... and light to meet it',
      title: 'Star Wars: The Last Jedi',
      video: false,
      vote_average: 6.818,
      vote_count: 14443,
    },
  },
  {
    adult: false,
    backdrop_path: '/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg',
    genre_ids: [12, 28, 878],
    id: 140607,
    original_language: 'en',
    original_title: 'Star Wars: The Force Awakens',
    overview:
      'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
    popularity: 59.45,
    poster_path: '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
    release_date: '2015-12-15',
    title: 'Star Wars: The Force Awakens',
    video: false,
    vote_average: 7.289,
    vote_count: 18507,
    details: {
      adult: false,
      backdrop_path: '/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 245000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage: 'http://www.starwars.com/films/star-wars-episode-vii',
      id: 140607,
      imdb_id: 'tt2488496',
      original_language: 'en',
      original_title: 'Star Wars: The Force Awakens',
      overview:
        'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
      popularity: 59.45,
      poster_path: '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 11461,
          logo_path: '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
          name: 'Bad Robot',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2015-12-15',
      revenue: 2068223624,
      runtime: 136,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Every generation has a story.',
      title: 'Star Wars: The Force Awakens',
      video: false,
      vote_average: 7.289,
      vote_count: 18507,
    },
  },
  {
    adult: false,
    backdrop_path: '/jOzrELAzFxtMx2I4uDGHOotdfsS.jpg',
    genre_ids: [12, 28, 878],
    id: 181812,
    original_language: 'en',
    original_title: 'Star Wars: The Rise of Skywalker',
    overview:
      'The surviving Resistance faces the First Order once again as the journey of Rey, Finn and Poe Dameron continues. With the power and knowledge of generations behind them, the final battle begins.',
    popularity: 76.735,
    poster_path: '/db32LaOibwEliAmSL2jjDF6oDdj.jpg',
    release_date: '2019-12-18',
    title: 'Star Wars: The Rise of Skywalker',
    video: false,
    vote_average: 6.355,
    vote_count: 9157,
    details: {
      adult: false,
      backdrop_path: '/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 245000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage: 'http://www.starwars.com/films/star-wars-episode-vii',
      id: 140607,
      imdb_id: 'tt2488496',
      original_language: 'en',
      original_title: 'Star Wars: The Force Awakens',
      overview:
        'Thirty years after defeating the Galactic Empire, Han Solo and his allies face a new threat from the evil Kylo Ren and his army of Stormtroopers.',
      popularity: 59.45,
      poster_path: '/wqnLdwVXoBjKibFRR5U3y0aDUhs.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 11461,
          logo_path: '/p9FoEt5shEKRWRKVIlvFaEmRnun.png',
          name: 'Bad Robot',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2015-12-15',
      revenue: 2068223624,
      runtime: 136,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Every generation has a story.',
      title: 'Star Wars: The Force Awakens',
      video: false,
      vote_average: 7.289,
      vote_count: 18507,
    },
  },
  {
    adult: false,
    backdrop_path: '/iflKt34Ck2JpY2PY9wW1zwdJgJi.jpg',
    genre_ids: [16, 878, 12, 10751],
    id: 782054,
    original_language: 'ja',
    original_title: '映画ドラえもん のび太の宇宙小戦争 2021',
    overview:
      'One day during summer vacation, a palm-sized alien named Papi appears from a small rocket that Nobita picks up. He is the president of Pirika, a small planet in outer space, and has come to Earth to escape the rebels. Doraemon and his friends are puzzled by Papi’s small size, but as they play together using the secret tool “Small Light”, they gradually become friends. However, a whale-shaped space battleship comes to earth and attacks Doraemon, Nobita and the others in order to capture Papi. Feeling responsible for getting everyone involved, Papi tries to stand up to the rebels. Doraemon and his friends leave for the planet Pirika to protect their dear friend and his home.',
    popularity: 20.297,
    poster_path: '/48gKZioIDeUOI0afbYv3kh9u9RQ.jpg',
    release_date: '2022-03-04',
    title: "Doraemon: Nobita's Little Star Wars 2021",
    video: false,
    vote_average: 6,
    vote_count: 103,
    details: {
      adult: false,
      backdrop_path: '/iflKt34Ck2JpY2PY9wW1zwdJgJi.jpg',
      belongs_to_collection: {
        id: 148065,
        name: 'Doraemon Collection',
        poster_path: '/4TLSP1KD1uAlp2q1rTrc6SFlktX.jpg',
        backdrop_path: '/rc6OFcSasL5YxBRPUQVwxmVF6h5.jpg',
      },
      budget: 0,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 10751,
          name: 'Family',
        },
      ],
      homepage: 'https://doraeiga.com/2021/',
      id: 782054,
      imdb_id: 'tt13740078',
      original_language: 'ja',
      original_title: '映画ドラえもん のび太の宇宙小戦争 2021',
      overview:
        'One day during summer vacation, a palm-sized alien named Papi appears from a small rocket that Nobita picks up. He is the president of Pirika, a small planet in outer space, and has come to Earth to escape the rebels. Doraemon and his friends are puzzled by Papi’s small size, but as they play together using the secret tool “Small Light”, they gradually become friends. However, a whale-shaped space battleship comes to earth and attacks Doraemon, Nobita and the others in order to capture Papi. Feeling responsible for getting everyone involved, Papi tries to stand up to the rebels. Doraemon and his friends leave for the planet Pirika to protect their dear friend and his home.',
      popularity: 20.297,
      poster_path: '/48gKZioIDeUOI0afbYv3kh9u9RQ.jpg',
      production_companies: [
        {
          id: 5141,
          logo_path: '/fK2QKfHdSdw42Xx4MiD7KhDufBV.png',
          name: 'Shin-Ei Animation',
          origin_country: 'JP',
        },
        {
          id: 15329,
          logo_path: null,
          name: 'Fujiko Productions',
          origin_country: 'JP',
        },
        {
          id: 9149,
          logo_path: '/isLUpud9N56ifftJZ4XvzwBBpoG.png',
          name: 'Shogakukan',
          origin_country: 'JP',
        },
        {
          id: 9300,
          logo_path: '/9sSD1XufVCJWAadNiC9Mwu994VD.png',
          name: 'TV Asahi',
          origin_country: 'JP',
        },
        {
          id: 173235,
          logo_path: null,
          name: 'ADK Emotions',
          origin_country: 'JP',
        },
        {
          id: 12655,
          logo_path: '/dfGqf2NoMVPrDywDL90D5HAhBlW.png',
          name: 'Shogakukan-Shueisha Productions',
          origin_country: 'JP',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'JP',
          name: 'Japan',
        },
      ],
      release_date: '2022-03-04',
      revenue: 0,
      runtime: 108,
      spoken_languages: [
        {
          english_name: 'Japanese',
          iso_639_1: 'ja',
          name: '日本語',
        },
      ],
      status: 'Released',
      tagline: '',
      title: "Doraemon: Nobita's Little Star Wars 2021",
      video: false,
      vote_average: 6,
      vote_count: 103,
    },
  },
  {
    adult: false,
    backdrop_path: '/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg',
    genre_ids: [28, 12, 878],
    id: 330459,
    original_language: 'en',
    original_title: 'Rogue One: A Star Wars Story',
    overview:
      'A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.',
    popularity: 43.121,
    poster_path: '/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg',
    release_date: '2016-12-14',
    title: 'Rogue One: A Star Wars Story',
    video: false,
    vote_average: 7.49,
    vote_count: 14476,
    details: {
      adult: false,
      backdrop_path: '/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg',
      belongs_to_collection: null,
      budget: 200000000,
      genres: [
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage: 'http://www.starwars.com/films/rogue-one',
      id: 330459,
      imdb_id: 'tt3748528',
      original_language: 'en',
      original_title: 'Rogue One: A Star Wars Story',
      overview:
        'A rogue band of resistance fighters unite for a mission to steal the Death Star plans and bring a new hope to the galaxy.',
      popularity: 43.121,
      poster_path: '/i0yw1mFbB7sNGHCs7EXZPzFkdA1.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2016-12-14',
      revenue: 1056057273,
      runtime: 133,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'A Rebellion Built on Hope',
      title: 'Rogue One: A Star Wars Story',
      video: false,
      vote_average: 7.49,
      vote_count: 14476,
    },
  },
  {
    adult: false,
    backdrop_path: '/ojHCeDULAkQK25700fhRU75Tur2.jpg',
    genre_ids: [878, 12, 28],
    id: 348350,
    original_language: 'en',
    original_title: 'Solo: A Star Wars Story',
    overview:
      'Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.',
    popularity: 50.457,
    poster_path: '/3IGbjc5ZC5yxim5W0sFING2kdcz.jpg',
    release_date: '2018-05-15',
    title: 'Solo: A Star Wars Story',
    video: false,
    vote_average: 6.564,
    vote_count: 7982,
    details: {
      adult: false,
      backdrop_path: '/ojHCeDULAkQK25700fhRU75Tur2.jpg',
      belongs_to_collection: null,
      budget: 250000000,
      genres: [
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
      ],
      homepage: 'https://www.starwars.com/films/solo',
      id: 348350,
      imdb_id: 'tt3778644',
      original_language: 'en',
      original_title: 'Solo: A Star Wars Story',
      overview:
        'Through a series of daring escapades deep within a dark and dangerous criminal underworld, Han Solo meets his mighty future copilot Chewbacca and encounters the notorious gambler Lando Calrissian.',
      popularity: 50.457,
      poster_path: '/3IGbjc5ZC5yxim5W0sFING2kdcz.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 47706,
          logo_path: null,
          name: 'Allison Shearmur Productions',
          origin_country: 'US',
        },
        {
          id: 23,
          logo_path: '/bJOFo2ufq7iFC1F4qZm8aLxF5aS.png',
          name: 'Imagine Entertainment',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2018-05-15',
      revenue: 392952373,
      runtime: 135,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Never tell him the odds.',
      title: 'Solo: A Star Wars Story',
      video: false,
      vote_average: 6.564,
      vote_count: 7982,
    },
  },
  {
    adult: false,
    backdrop_path: '/wDe8LzwuvHYYiuwyNfxdYQq8ti4.jpg',
    genre_ids: [12, 28, 878],
    id: 1893,
    original_language: 'en',
    original_title: 'Star Wars: Episode I - The Phantom Menace',
    overview:
      'Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.',
    popularity: 46.581,
    poster_path: '/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg',
    release_date: '1999-05-19',
    title: 'Star Wars: Episode I - The Phantom Menace',
    video: false,
    vote_average: 6.536,
    vote_count: 13689,
    details: {
      adult: false,
      backdrop_path: '/wDe8LzwuvHYYiuwyNfxdYQq8ti4.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 115000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage:
        'http://www.starwars.com/films/star-wars-episode-i-the-phantom-menace',
      id: 1893,
      imdb_id: 'tt0120915',
      original_language: 'en',
      original_title: 'Star Wars: Episode I - The Phantom Menace',
      overview:
        'Anakin Skywalker, a young slave strong with the Force, is discovered on Tatooine. Meanwhile, the evil Sith have returned, enacting their plot for revenge against the Jedi.',
      popularity: 46.581,
      poster_path: '/6wkfovpn7Eq8dYNKaG5PY3q2oq6.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '1999-05-19',
      revenue: 924317558,
      runtime: 136,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline:
        'Every generation has a legend. Every journey has a first step. Every saga has a beginning.',
      title: 'Star Wars: Episode I - The Phantom Menace',
      video: false,
      vote_average: 6.536,
      vote_count: 13689,
    },
  },
  {
    adult: false,
    backdrop_path: '/xEdnGUc8KeZ7h0eEgSN3ERhjgL0.jpg',
    genre_ids: [16, 28, 878, 12],
    id: 12180,
    original_language: 'en',
    original_title: 'Star Wars: The Clone Wars',
    overview:
      'As the Clone Wars sweep through the galaxy, the heroic Jedi Knights struggle to maintain order and restore peace. More and more systems are falling prey to the forces of the dark side as the Galactic Republic slips further and further under the sway of the Separatists and their never-ending droid army. Anakin Skywalker and his Padawan learner Ahsoka Tano find themselves on a mission with far-reaching consequences, one that brings them face-to-face with crime lord Jabba the Hutt. But Count Dooku and his sinister agents, including the nefarious Asajj Ventress, will stop at nothing to ensure that Anakin and Ahsoka fail at their quest. Meanwhile, on the front lines of the Clone Wars, Obi-Wan Kenobi and Master Yoda lead the massive clone army in a valiant effort to resist the forces of the dark side...',
    popularity: 18.889,
    poster_path: '/iJQfixW818LUdSXlCDL3JZm0S0g.jpg',
    release_date: '2008-08-05',
    title: 'Star Wars: The Clone Wars',
    video: false,
    vote_average: 6.117,
    vote_count: 1858,
    details: {
      adult: false,
      backdrop_path: '/xEdnGUc8KeZ7h0eEgSN3ERhjgL0.jpg',
      belongs_to_collection: null,
      budget: 8500000,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 12,
          name: 'Adventure',
        },
      ],
      homepage:
        'https://www.lucasfilm.com/productions/star-wars-the-clone-wars/',
      id: 12180,
      imdb_id: 'tt1185834',
      original_language: 'en',
      original_title: 'Star Wars: The Clone Wars',
      overview:
        'As the Clone Wars sweep through the galaxy, the heroic Jedi Knights struggle to maintain order and restore peace. More and more systems are falling prey to the forces of the dark side as the Galactic Republic slips further and further under the sway of the Separatists and their never-ending droid army. Anakin Skywalker and his Padawan learner Ahsoka Tano find themselves on a mission with far-reaching consequences, one that brings them face-to-face with crime lord Jabba the Hutt. But Count Dooku and his sinister agents, including the nefarious Asajj Ventress, will stop at nothing to ensure that Anakin and Ahsoka fail at their quest. Meanwhile, on the front lines of the Clone Wars, Obi-Wan Kenobi and Master Yoda lead the massive clone army in a valiant effort to resist the forces of the dark side...',
      popularity: 18.889,
      poster_path: '/iJQfixW818LUdSXlCDL3JZm0S0g.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 108270,
          logo_path: '/eDWGeg5tdVNcI8aBaaJ21bEBtFa.png',
          name: 'Lucasfilm Animation',
          origin_country: 'US',
        },
        {
          id: 174,
          logo_path: '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png',
          name: 'Warner Bros. Pictures',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2008-08-05',
      revenue: 68282844,
      runtime: 98,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: "Prepare to see Star Wars like you've never seen it before.",
      title: 'Star Wars: The Clone Wars',
      video: false,
      vote_average: 6.117,
      vote_count: 1858,
    },
  },
  {
    adult: false,
    backdrop_path: '/5vDuLrjJXFS9PTF7Q1xzobmYKR9.jpg',
    genre_ids: [12, 28, 878],
    id: 1895,
    original_language: 'en',
    original_title: 'Star Wars: Episode III - Revenge of the Sith',
    overview:
      'The evil Darth Sidious enacts his final plan for unlimited power -- and the heroic Jedi Anakin Skywalker must choose a side.',
    popularity: 42.236,
    poster_path: '/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg',
    release_date: '2005-05-17',
    title: 'Star Wars: Episode III - Revenge of the Sith',
    video: false,
    vote_average: 7.413,
    vote_count: 12880,
    details: {
      adult: false,
      backdrop_path: '/5vDuLrjJXFS9PTF7Q1xzobmYKR9.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 113000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage:
        'http://www.starwars.com/films/star-wars-episode-iii-revenge-of-the-sith',
      id: 1895,
      imdb_id: 'tt0121766',
      original_language: 'en',
      original_title: 'Star Wars: Episode III - Revenge of the Sith',
      overview:
        'The evil Darth Sidious enacts his final plan for unlimited power -- and the heroic Jedi Anakin Skywalker must choose a side.',
      popularity: 42.236,
      poster_path: '/xfSAoBEm9MNBjmlNcDYLvLSMlnq.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2005-05-17',
      revenue: 850000000,
      runtime: 140,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'The saga is complete.',
      title: 'Star Wars: Episode III - Revenge of the Sith',
      video: false,
      vote_average: 7.413,
      vote_count: 12880,
    },
  },
  {
    adult: false,
    backdrop_path: '/abwxHfymXGAbbH3lo9PDEJEfvtW.jpg',
    genre_ids: [12, 28, 878],
    id: 1894,
    original_language: 'en',
    original_title: 'Star Wars: Episode II - Attack of the Clones',
    overview:
      'Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.',
    popularity: 39.688,
    poster_path: '/oZNPzxqM2s5DyVWab09NTQScDQt.jpg',
    release_date: '2002-05-15',
    title: 'Star Wars: Episode II - Attack of the Clones',
    video: false,
    vote_average: 6.552,
    vote_count: 12411,
    details: {
      adult: false,
      backdrop_path: '/abwxHfymXGAbbH3lo9PDEJEfvtW.jpg',
      belongs_to_collection: {
        id: 10,
        name: 'Star Wars Collection',
        poster_path: '/gq5Wi7i4SF3lo4HHkJasDV95xI9.jpg',
        backdrop_path: '/zZDkgOmFMVYpGAkR9Tkxw0CRnxX.jpg',
      },
      budget: 120000000,
      genres: [
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
      ],
      homepage: '',
      id: 1894,
      imdb_id: 'tt0121765',
      original_language: 'en',
      original_title: 'Star Wars: Episode II - Attack of the Clones',
      overview:
        'Following an assassination attempt on Senator Padmé Amidala, Jedi Knights Anakin Skywalker and Obi-Wan Kenobi investigate a mysterious plot that could change the galaxy forever.',
      popularity: 39.688,
      poster_path: '/oZNPzxqM2s5DyVWab09NTQScDQt.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2002-05-15',
      revenue: 649398328,
      runtime: 142,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'A Jedi Shall Not Know Anger. Nor Hatred. Nor Love.',
      title: 'Star Wars: Episode II - Attack of the Clones',
      video: false,
      vote_average: 6.552,
      vote_count: 12411,
    },
  },
  {
    adult: false,
    backdrop_path: '/f53Jujiap580mgfefID0T0g2e17.jpg',
    genre_ids: [16, 10751, 878, 35, 28, 27, 10770],
    id: 857702,
    original_language: 'en',
    original_title: 'LEGO Star Wars Terrifying Tales',
    overview:
      'Poe Dameron and BB-8 must face the greedy crime boss Graballa the Hutt, who has purchased Darth Vader’s castle and is renovating it into the galaxy’s first all-inclusive Sith-inspired luxury hotel.',
    popularity: 20.103,
    poster_path: '/fYiaBZDjyXjvlY6EDZMAxIhBO1I.jpg',
    release_date: '2021-10-01',
    title: 'LEGO Star Wars Terrifying Tales',
    video: false,
    vote_average: 6.8,
    vote_count: 223,
    details: {
      adult: false,
      backdrop_path: '/f53Jujiap580mgfefID0T0g2e17.jpg',
      belongs_to_collection: {
        id: 1004630,
        name: 'LEGO Star Wars (Seasonal) Collection',
        poster_path: '/jHITUzB6fZVOYZ13YCqVTS06iyw.jpg',
        backdrop_path: '/cVYUqWzzUSrkLQwb4jlWAkaFCAX.jpg',
      },
      budget: 0,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 10751,
          name: 'Family',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 35,
          name: 'Comedy',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 27,
          name: 'Horror',
        },
        {
          id: 10770,
          name: 'TV Movie',
        },
      ],
      homepage:
        'https://www.disneyplus.com/movies/lego-star-wars-terrifying-tales/4CysUZZ8Cfmw',
      id: 857702,
      imdb_id: 'tt15164924',
      original_language: 'en',
      original_title: 'LEGO Star Wars Terrifying Tales',
      overview:
        'Poe Dameron and BB-8 must face the greedy crime boss Graballa the Hutt, who has purchased Darth Vader’s castle and is renovating it into the galaxy’s first all-inclusive Sith-inspired luxury hotel.',
      popularity: 20.103,
      poster_path: '/fYiaBZDjyXjvlY6EDZMAxIhBO1I.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 71739,
          logo_path: '/9VhJRP6kUOJWH5QvSTeqMQFWuql.png',
          name: 'Atomic Cartoons',
          origin_country: 'CA',
        },
        {
          id: 4081,
          logo_path: '/9Q0SyrhQD61wWbz5KJOkL6tu2mg.png',
          name: 'LEGO',
          origin_country: 'DK',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'CA',
          name: 'Canada',
        },
        {
          iso_3166_1: 'DK',
          name: 'Denmark',
        },
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2021-10-01',
      revenue: 0,
      runtime: 45,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'Rest in pieces.',
      title: 'LEGO Star Wars Terrifying Tales',
      video: false,
      vote_average: 6.8,
      vote_count: 223,
    },
  },
  {
    adult: false,
    backdrop_path: '/ae9xlnkS2qb5Dy9Mtlu68AWh42O.jpg',
    genre_ids: [14, 878, 10751, 10770],
    id: 74849,
    original_language: 'en',
    original_title: 'The Star Wars Holiday Special',
    overview:
      'Luke Skywalker and Han Solo battle evil Imperial forces to help Chewbacca reach his imperiled family on the Wookiee planet - in time for Life Day, their most important day of the year!',
    popularity: 22.877,
    poster_path: '/eRSKviGcTqHd34vCLjcztJF6Eaw.jpg',
    release_date: '1978-12-01',
    title: 'The Star Wars Holiday Special',
    video: false,
    vote_average: 3.4,
    vote_count: 421,
    details: {
      adult: false,
      backdrop_path: '/ae9xlnkS2qb5Dy9Mtlu68AWh42O.jpg',
      belongs_to_collection: null,
      budget: 0,
      genres: [
        {
          id: 14,
          name: 'Fantasy',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 10751,
          name: 'Family',
        },
        {
          id: 10770,
          name: 'TV Movie',
        },
      ],
      homepage: '',
      id: 74849,
      imdb_id: 'tt0193524',
      original_language: 'en',
      original_title: 'The Star Wars Holiday Special',
      overview:
        'Luke Skywalker and Han Solo battle evil Imperial forces to help Chewbacca reach his imperiled family on the Wookiee planet - in time for Life Day, their most important day of the year!',
      popularity: 22.877,
      poster_path: '/eRSKviGcTqHd34vCLjcztJF6Eaw.jpg',
      production_companies: [
        {
          id: 1556,
          logo_path: '/31h94rG9hzjprXoYNy3L1ErUya2.png',
          name: '20th Century Fox Television',
          origin_country: 'US',
        },
        {
          id: 3143,
          logo_path: null,
          name: 'Smith-Hemion Productions',
          origin_country: '',
        },
        {
          id: 5484,
          logo_path: null,
          name: 'Winters Hollywood Entertainment Holdings Corporation',
          origin_country: 'US',
        },
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '1978-12-01',
      revenue: 0,
      runtime: 97,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'A long time ago, in a galaxy far, far away...',
      title: 'The Star Wars Holiday Special',
      video: false,
      vote_average: 3.4,
      vote_count: 421,
    },
  },
  {
    adult: false,
    backdrop_path: '/1Lhc32P0a62BgMFgd20wXR1osR3.jpg',
    genre_ids: [16, 10751, 12, 35, 878, 28, 10770],
    id: 732670,
    original_language: 'en',
    original_title: 'LEGO Star Wars Holiday Special',
    overview:
      'As her friends prep for a Life Day holiday celebration, Rey journeys with BB-8 on a quest to gain a deeper knowledge of the Force at a mysterious Jedi Temple. There, she embarks on a cross-timeline adventure through beloved moments in Star Wars history, coming into contact with iconic heroes and villains from all eras of the saga. But will she make it back in time for the Life Day feast?',
    popularity: 18.824,
    poster_path: '/zyzJSI7UZZzz5Toj10rYGF5689z.jpg',
    release_date: '2020-11-17',
    title: 'LEGO Star Wars Holiday Special',
    video: false,
    vote_average: 6.596,
    vote_count: 293,
    details: {
      adult: false,
      backdrop_path: '/1Lhc32P0a62BgMFgd20wXR1osR3.jpg',
      belongs_to_collection: {
        id: 1004630,
        name: 'LEGO Star Wars (Seasonal) Collection',
        poster_path: '/jHITUzB6fZVOYZ13YCqVTS06iyw.jpg',
        backdrop_path: '/cVYUqWzzUSrkLQwb4jlWAkaFCAX.jpg',
      },
      budget: 0,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 10751,
          name: 'Family',
        },
        {
          id: 12,
          name: 'Adventure',
        },
        {
          id: 35,
          name: 'Comedy',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 10770,
          name: 'TV Movie',
        },
      ],
      homepage:
        'https://www.disneyplus.com/movies/lego-star-wars-holiday-special/22xf1U47vVe0',
      id: 732670,
      imdb_id: 'tt12885438',
      original_language: 'en',
      original_title: 'LEGO Star Wars Holiday Special',
      overview:
        'As her friends prep for a Life Day holiday celebration, Rey journeys with BB-8 on a quest to gain a deeper knowledge of the Force at a mysterious Jedi Temple. There, she embarks on a cross-timeline adventure through beloved moments in Star Wars history, coming into contact with iconic heroes and villains from all eras of the saga. But will she make it back in time for the Life Day feast?',
      popularity: 18.824,
      poster_path: '/zyzJSI7UZZzz5Toj10rYGF5689z.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 4081,
          logo_path: '/9Q0SyrhQD61wWbz5KJOkL6tu2mg.png',
          name: 'LEGO',
          origin_country: 'DK',
        },
        {
          id: 71739,
          logo_path: '/9VhJRP6kUOJWH5QvSTeqMQFWuql.png',
          name: 'Atomic Cartoons',
          origin_country: 'CA',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'CA',
          name: 'Canada',
        },
        {
          iso_3166_1: 'DK',
          name: 'Denmark',
        },
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2020-11-17',
      revenue: 0,
      runtime: 44,
      spoken_languages: [
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: 'To: Luke. From: Your father.',
      title: 'LEGO Star Wars Holiday Special',
      video: false,
      vote_average: 6.596,
      vote_count: 293,
    },
  },
  {
    adult: false,
    backdrop_path: '/l3OSKCM0oBOGuioC2jeaeeV8m4I.jpg',
    genre_ids: [16, 35, 878, 28, 10770],
    id: 42979,
    original_language: 'en',
    original_title: 'Robot Chicken: Star Wars',
    overview:
      'A series of 30 sketches, following the hilarious antics of various characters from a galaxy, far, far away.',
    popularity: 11.698,
    poster_path: '/h44WN4mVJ6wEpJgLaaNoFjv0NAo.jpg',
    release_date: '2007-07-17',
    title: 'Robot Chicken: Star Wars',
    video: false,
    vote_average: 7.229,
    vote_count: 236,
    details: {
      adult: false,
      backdrop_path: '/l3OSKCM0oBOGuioC2jeaeeV8m4I.jpg',
      belongs_to_collection: {
        id: 141748,
        name: 'Robot Chicken - Star Wars Collection',
        poster_path: '/m6tP4z5IIk8lIsBTpXu5H0B8hO3.jpg',
        backdrop_path: null,
      },
      budget: 0,
      genres: [
        {
          id: 16,
          name: 'Animation',
        },
        {
          id: 35,
          name: 'Comedy',
        },
        {
          id: 878,
          name: 'Science Fiction',
        },
        {
          id: 28,
          name: 'Action',
        },
        {
          id: 10770,
          name: 'TV Movie',
        },
      ],
      homepage: '',
      id: 42979,
      imdb_id: 'tt1020990',
      original_language: 'en',
      original_title: 'Robot Chicken: Star Wars',
      overview:
        'A series of 30 sketches, following the hilarious antics of various characters from a galaxy, far, far away.',
      popularity: 11.698,
      poster_path: '/h44WN4mVJ6wEpJgLaaNoFjv0NAo.jpg',
      production_companies: [
        {
          id: 1,
          logo_path: '/tlVSws0RvvtPBwViUyOFAO0vcQS.png',
          name: 'Lucasfilm Ltd.',
          origin_country: 'US',
        },
        {
          id: 67233,
          logo_path: '/yDSof0ATfVdv0swak8TAEPFHk0K.png',
          name: 'Stoopid Monkey',
          origin_country: 'US',
        },
        {
          id: 65451,
          logo_path: null,
          name: 'Sony Pictures Digital',
          origin_country: '',
        },
        {
          id: 81667,
          logo_path: '/Am06MBFNH0OLe3m5MEhdyIFeYWh.png',
          name: 'ShadowMachine',
          origin_country: 'US',
        },
      ],
      production_countries: [
        {
          iso_3166_1: 'US',
          name: 'United States of America',
        },
      ],
      release_date: '2007-07-17',
      revenue: 0,
      runtime: 23,
      spoken_languages: [
        {
          english_name: 'German',
          iso_639_1: 'de',
          name: 'Deutsch',
        },
        {
          english_name: 'English',
          iso_639_1: 'en',
          name: 'English',
        },
      ],
      status: 'Released',
      tagline: "Spend Father's Day with who really raised you... Star Wars.",
      title: 'Robot Chicken: Star Wars',
      video: false,
      vote_average: 7.229,
      vote_count: 236,
    },
  },
];
